services:
  - type: web
    name: restaurante-streamlit
    env: python
    plan: free
    region: ohio
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: STREAMLIT_SERVER_HEADLESS
        value: true